### full post request
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Post title",
  "description": "Some description",
  "content": "Some meaningful (not sure) code",
  "expirationTimeInDays": 10
}

### post request to undefined subresource
POST http://localhost:8080/posts/beb/ra
Content-Type: application/json

{
  "title": "Post title",
  "description": "Some description",
  "content": "Some meaningful (not sure) code",
  "expirationTimeInDays": 10
}

### post without optional fields
POST http://localhost:8080/posts
Content-Type: application/json

{
  "content": "Some meaningful (not sure) code"
}

### post with missing required field
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Post title",
  "description": "Some description",
  "expirationTimeInDays": 10
}

### post with constraint violation
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Post title",
  "description": "Some description",
  "content": "Some meaningful (not sure) code",
  "expirationTimeInDays": 31
}

### post with incorrect json
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Post title",
  "description": "Some description",
  "content": "Some meaningful (not sure) code"
  "expirationTimeInDays": 10
}



### get for existent post
GET http://localhost:8080/posts/1
Accept: application/json

### get for non-existent post
GET http://localhost:8080/posts/100
Accept: application/json

### get with incorrect id format
GET http://localhost:8080/posts/abc
Accept: application/json

### get for undefined subresource
GET http://localhost:8080/posts/1/bebra
Accept: application/json



### get statistics
GET http://localhost:8080/stats
Accept: application/json



### get for undefined page
GET http://localhost:8080/bebra
Accept: application/json